name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: compile
      id: compile
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: compile
        setup-command: ''
        command: g++ -std=c++17 -Wall -Wextra -O2 -o lab09 lab09-main.cpp
        timeout: 10
        max-score: 10
    - name: run
      id: run
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: run
        setup-command: ''
        command: "./lab09"
        input: ''
        expected-output:
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        COMPILE_RESULTS: "${{steps.compile.outputs.result}}"
        RUN_RESULTS: "${{steps.run.outputs.result}}"
      with:
        runners: compile,run
